version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/examples/tcp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/examples/udp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/examples/tcp/e2e"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/examples/udp/e2e"
    schedule:
      interval: "weekly"
