version: "3"

tasks:
  dev:
    desc: Enter development shell
    cmds:
      - nix develop

  build:
    desc: Build rns-tcp-iface
    cmds:
      - nix build

  build-tcp:
    desc: Build rns-tcp-iface with go
    cmds:
      - cd examples/tcp && go build -o rns-tcp-iface .

  update:
    desc: Update gomod2nix.toml after changing dependencies
    cmds:
      - gomod2nix

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run

  test:
    desc: Run tests
    cmds:
      - go test ./...

  test-all:
    desc: Run all tests including examples
    cmds:
      - go test ./...
      - cd examples/tcp && go vet ./...

  check:
    desc: Run nix flake check
    cmds:
      - nix flake check
